
function(test_scope var)
	set(var "change")
	set(test_str "test_scope" PARENT_SCOPE)
	set(CMAKE_CXX_STANDARD 20)
endfunction()

macro(test_list_mac tmp)
	message("test_list_mac========== ${ARGN}")
	message(${tmp})
	message(${${tmp}})
	list(REMOVE_DUPLICATES ${tmp})
	message(${${tmp}})
endmacro()

function(test_list_func tmp)
	message("test_list_func========== ${ARGN}")
	message(${tmp})
	message(${${tmp}})
	list(REMOVE_DUPLICATES ${tmp})
	message(${${tmp}})
endfunction()

macro(test_bool_mac var)
	message("test_bool_mac ${var}")
	if(var)
		message("1")
	endif()
	if(${var})
		message("2")
	endif()
	if(${${var}})
		message("3")
	endif()
	set(var OFF)
	set(${var} OFF)
	set(${${var}} OFF)
endmacro()

function(test_bool_func var)
	message("test_bool_func ${var}")
	if(var)
		message("1")
	endif()
	if(${var})
		message("2")
	endif()
	if(${${var}})
		message("3")
	endif()
	set(var OFF)
	set(${var} OFF)
	set(${${var}} OFF)
endfunction()