# cmake config
# bms - base make set

function(bms_standard isc ver_no)
	bm_boundary("bms_standard" ON OFF)
	message("${MSG_PRE} is c(${isc}) version(${ver_no}) required(${ARGV2}) open_extension(${ARGV3})")
	if(isc)
		set(CMAKE_C_STANDARD ${ver_no} PARENT_SCOPE)
		message("${MSG_PRE} c version(${ver_no}) config")
		if(DEFINED ARGV2 AND ARGV2)
			set(CMAKE_C_STANDARD_REQUIRED ON PARENT_SCOPE)
			message("${MSG_PRE} c(${ver_no}) required")
		endif()
		if(DEFINED ARGV3 AND ARGV3)
			set(CMAKE_C_EXTENSIONS ON PARENT_SCOPE)
			message("${MSG_PRE} c(${ver_no}) extension open")
		endif()
	else()
		set(CMAKE_CXX_STANDARD ${ver_no} PARENT_SCOPE)
		message("${MSG_PRE} cxx(${ver_no}) config")
		if(DEFINED ARGV2 AND ARGV2)
			set(CMAKE_CXX_STANDARD_REQUIRED ON PARENT_SCOPE)
			message("${MSG_PRE} cxx(${ver_no}) required")
		endif()
		if(DEFINED ARGV3 AND ARGV3)
			set(CMAKE_CXX_EXTENSIONS ON PARENT_SCOPE)
			message("${MSG_PRE} cxx(${ver_no}) extension open")
		endif()
	endif()
	bm_boundary("bms_standard" OFF OFF)
endfunction()
